version: '3.9'

services:
  gophermart:
    build: ./
    command: ./gophermart
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SIGNING_KEY: "qwerty1234"
      RUN_ADDRESS: "localhost:8000"
      DATABASE_URI: "postgres://postgres:qwerty1234@db:5432/postgres"

  db:
    restart: always
    container_name: gophermart_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwerty1234
    ports:
      - 5432:5432